#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added ACL originator"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2785a435103a'
down_revision = 'a640789a66a8'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invenio_acls_elasticsearchacl', sa.Column('originator_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_invenio_acls_elasticsearchacl_originator_id'), 'invenio_acls_elasticsearchacl', ['originator_id'], unique=False)
    op.create_foreign_key(op.f('fk_invenio_acls_elasticsearchacl_originator_id_accounts_user'), 'invenio_acls_elasticsearchacl', 'accounts_user', ['originator_id'], ['id'], ondelete='CASCADE')
    op.add_column('invenio_acls_elasticsearchacl_version', sa.Column('originator_id', sa.Integer(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_invenio_acls_elasticsearchacl_version_originator_id'), 'invenio_acls_elasticsearchacl_version', ['originator_id'], unique=False)
    op.add_column('invenio_acls_idacl', sa.Column('originator_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_invenio_acls_idacl_originator_id'), 'invenio_acls_idacl', ['originator_id'], unique=False)
    op.create_foreign_key(op.f('fk_invenio_acls_idacl_originator_id_accounts_user'), 'invenio_acls_idacl', 'accounts_user', ['originator_id'], ['id'], ondelete='CASCADE')
    op.add_column('invenio_acls_idacl_version', sa.Column('originator_id', sa.Integer(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_invenio_acls_idacl_version_originator_id'), 'invenio_acls_idacl_version', ['originator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invenio_acls_idacl_version_originator_id'), table_name='invenio_acls_idacl_version')
    op.drop_column('invenio_acls_idacl_version', 'originator_id')
    op.drop_constraint(op.f('fk_invenio_acls_idacl_originator_id_accounts_user'), 'invenio_acls_idacl', type_='foreignkey')
    op.drop_index(op.f('ix_invenio_acls_idacl_originator_id'), table_name='invenio_acls_idacl')
    op.drop_column('invenio_acls_idacl', 'originator_id')
    op.drop_index(op.f('ix_invenio_acls_elasticsearchacl_version_originator_id'), table_name='invenio_acls_elasticsearchacl_version')
    op.drop_column('invenio_acls_elasticsearchacl_version', 'originator_id')
    op.drop_constraint(op.f('fk_invenio_acls_elasticsearchacl_originator_id_accounts_user'), 'invenio_acls_elasticsearchacl', type_='foreignkey')
    op.drop_index(op.f('ix_invenio_acls_elasticsearchacl_originator_id'), table_name='invenio_acls_elasticsearchacl')
    op.drop_column('invenio_acls_elasticsearchacl', 'originator_id')
    # ### end Alembic commands ###
