#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added default acls"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '572cd81502b1'
down_revision = '2785a435103a'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invenio_acls_defaultacl_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('originator_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_invenio_acls_defaultacl_version'))
    )
    op.create_index(op.f('ix_invenio_acls_defaultacl_version_end_transaction_id'), 'invenio_acls_defaultacl_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_invenio_acls_defaultacl_version_operation_type'), 'invenio_acls_defaultacl_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_invenio_acls_defaultacl_version_originator_id'), 'invenio_acls_defaultacl_version', ['originator_id'], unique=False)
    op.create_index(op.f('ix_invenio_acls_defaultacl_version_transaction_id'), 'invenio_acls_defaultacl_version', ['transaction_id'], unique=False)
    op.create_table('invenio_acls_defaultacl',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('originator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['originator_id'], ['accounts_user.id'], name=op.f('fk_invenio_acls_defaultacl_originator_id_accounts_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invenio_acls_defaultacl'))
    )
    op.create_index(op.f('ix_invenio_acls_defaultacl_originator_id'), 'invenio_acls_defaultacl', ['originator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invenio_acls_defaultacl_originator_id'), table_name='invenio_acls_defaultacl')
    op.drop_table('invenio_acls_defaultacl')
    op.drop_index(op.f('ix_invenio_acls_defaultacl_version_transaction_id'), table_name='invenio_acls_defaultacl_version')
    op.drop_index(op.f('ix_invenio_acls_defaultacl_version_originator_id'), table_name='invenio_acls_defaultacl_version')
    op.drop_index(op.f('ix_invenio_acls_defaultacl_version_operation_type'), table_name='invenio_acls_defaultacl_version')
    op.drop_index(op.f('ix_invenio_acls_defaultacl_version_end_transaction_id'), table_name='invenio_acls_defaultacl_version')
    op.drop_table('invenio_acls_defaultacl_version')
    # ### end Alembic commands ###
