#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added continuum."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a640789a66a8'
down_revision = 'f723315b548a'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invenio_acls_elasticsearchacl_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('record_selector', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_invenio_acls_elasticsearchacl_version'))
    )
    op.create_index(op.f('ix_invenio_acls_elasticsearchacl_version_end_transaction_id'), 'invenio_acls_elasticsearchacl_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_invenio_acls_elasticsearchacl_version_operation_type'), 'invenio_acls_elasticsearchacl_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_invenio_acls_elasticsearchacl_version_transaction_id'), 'invenio_acls_elasticsearchacl_version', ['transaction_id'], unique=False)
    op.create_table('invenio_acls_idacl_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('record_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_invenio_acls_idacl_version'))
    )
    op.create_index(op.f('ix_invenio_acls_idacl_version_end_transaction_id'), 'invenio_acls_idacl_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_invenio_acls_idacl_version_operation_type'), 'invenio_acls_idacl_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_invenio_acls_idacl_version_transaction_id'), 'invenio_acls_idacl_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invenio_acls_idacl_version_transaction_id'), table_name='invenio_acls_idacl_version')
    op.drop_index(op.f('ix_invenio_acls_idacl_version_operation_type'), table_name='invenio_acls_idacl_version')
    op.drop_index(op.f('ix_invenio_acls_idacl_version_end_transaction_id'), table_name='invenio_acls_idacl_version')
    op.drop_table('invenio_acls_idacl_version')
    op.drop_index(op.f('ix_invenio_acls_elasticsearchacl_version_transaction_id'), table_name='invenio_acls_elasticsearchacl_version')
    op.drop_index(op.f('ix_invenio_acls_elasticsearchacl_version_operation_type'), table_name='invenio_acls_elasticsearchacl_version')
    op.drop_index(op.f('ix_invenio_acls_elasticsearchacl_version_end_transaction_id'), table_name='invenio_acls_elasticsearchacl_version')
    op.drop_table('invenio_acls_elasticsearchacl_version')
    # ### end Alembic commands ###
