#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create acl tables."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f723315b548a'
down_revision = '6d69e9abf6f2'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invenio_acls_elasticsearchacl',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('record_selector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invenio_acls_elasticsearchacl'))
    )
    op.create_table('invenio_acls_idacl',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indices', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('record_id', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invenio_acls_idacl'))
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invenio_acls_idacl')
    op.drop_table('invenio_acls_elasticsearchacl')
    # ### end Alembic commands ###
