#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""timestamped actors."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '06aae02f41ca'
down_revision = 'ec5cbec43ec8'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explicit_acls_actor', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('explicit_acls_actor', sa.Column('originator_id', sa.Integer(), nullable=False))
    op.add_column('explicit_acls_actor', sa.Column('updated', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_explicit_acls_actor_originator_id'), 'explicit_acls_actor', ['originator_id'], unique=False)
    op.create_foreign_key(op.f('fk_explicit_acls_actor_originator_id_accounts_user'), 'explicit_acls_actor', 'accounts_user', ['originator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_explicit_acls_actor_originator_id_accounts_user'), 'explicit_acls_actor', type_='foreignkey')
    op.drop_index(op.f('ix_explicit_acls_actor_originator_id'), table_name='explicit_acls_actor')
    op.drop_column('explicit_acls_actor', 'updated')
    op.drop_column('explicit_acls_actor', 'originator_id')
    op.drop_column('explicit_acls_actor', 'created')
    # ### end Alembic commands ###
