#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""SystemRole actor"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f135387190'
down_revision = '2cd83b6065cc'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explicit_acls_system_role', sa.Column('system_role', sa.String(), nullable=True))
    op.drop_column('explicit_acls_system_role', 'authenticated')
    op.drop_column('explicit_acls_system_role', 'anonymous')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explicit_acls_system_role', sa.Column('anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('explicit_acls_system_role', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('explicit_acls_system_role', 'system_role')
    # ### end Alembic commands ###
